### ISSUE TITLE
Install failed with error TS1192

### ISSUE THREAD

**Issue by mkyutani** [ryo-ma/dim#4]
dimインストール中にTS1192が発生するようになってしまいました。(再現性あり)

* エラー内容
```
error: TS1192 [ERROR]: Module '"https://jspm.dev/xlsx.js"' has no default export.
import xlsxlib from 'https://jspm.dev/xlsx'
       ~~~~~~~
    at https://deno.land/x/flat@0.0.13/src/xlsx.ts:1:8
```
* エラー生起タイミング：deno install
* バージョン等
```
# deno --version
deno 1.19.1 (release, x86_64-unknown-linux-gnu)
v8 9.9.115.7
typescript 4.5.2
# git for-each-ref
5383d922b715002dc8706fb6af8e4a53b125b8bd commit refs/heads/main
5383d922b715002dc8706fb6af8e4a53b125b8bd commit refs/remotes/origin/HEAD
5383d922b715002dc8706fb6af8e4a53b125b8bd commit refs/remotes/origin/main
8c54c493a4588103a9f715812e6f7dad467a9853 commit refs/tags/v0.1.3
5f4309e2f10008ad01582ccbc92ec7327a858df8 commit refs/tags/v0.1.4
b3092d7d4a9208437c60cae05de43a747503fbea commit refs/tags/v0.1.5
```

## 操作ログ

以下のような新しいubuntuコンテナの操作で再現しました。

```
$ sudo docker run -it --rm ubuntu /bin/bash
```

以下、コンテナ内操作。

* 必要なものをインストール
```
# apt update; apt upgrade
# apt install git curl unzip
```
* git config & SSH設定
* denoインストール
```
# curl -fsSL https://deno.land/install.sh | sh
# echo 'export DENO_INSTALL="/root/.deno"' >> ~/.bashrc
# echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> ~/.bashrc
# source ~/.bashrc
````
* dimインストール
```
# git clone git@github.com:ryo-ma/dim.git
# cd dim
# deno install --unstable --allow-read --allow-write --allow-run --allow-net dim.ts
Download https://cdn.skypack.dev/encoding-japanese
Download https://deno.land/std@0.105.0/fmt/colors.ts
Download https://deno.land/std@0.105.0/fs/mod.ts
...
Download https://deno.land/x/flat@0.0.13/src/xlsx-types.ts
Download https://jspm.dev/xlsx
...
Check file:///root/dim/dim.ts
error: TS1192 [ERROR]: Module '"https://jspm.dev/xlsx.js"' has no default export.
import xlsxlib from 'https://jspm.dev/xlsx'
       ~~~~~~~
    at https://deno.land/x/flat@0.0.13/src/xlsx.ts:1:8
```

**Comment by ryo-ma** [comment]
Update the flat version to the latest

https://github.com/githubocto/flat/issues/67#issuecomment-1025911772

**Comment by mkyutani** [comment]
Thx!
